### ISSUE TITLE
Revisar lista de palavras-chave e combinações para novas queries

### ISSUE THREAD

**Issue by ogecece** [okfn-brasil/observatorio-materiais#13]
DESCRIÇÃO:
A partir de uma primeira proposta da equipe de IC, a equipe de AP irá analisar a lista de palavras-chave atualizadas após a oficina (#7 ).

OBJETIVO:
Refinar lista e combinações de termos de busca.

DEFINIÇÃO DE PRONTO
Lista revisada pelas duas equipes e alinhada aos objetivos do primeiro relatório (panorama sobre a implantação de tecnologias na educação municipal).

**Comment by ogecece** [comment]
@adanibello

Essa é a sugestão de palavras-chave, mesclando a experiência dos pilotos com as indicações da 1ª oficina.

Explicando um pouco o formato:

O tema geral seria `Implantação de Tecnologias na Educação` e cada subtema tem suas `queries`. Cada query pode ter algumas variações que são separadas em `term_sets`. Cada term_set é na verdade uma sequência de conjuntos de sinônimos. Aqui, a ideia seria que o primeiro conjunto seria o conjunto do tipo de objeto, o segundo seria o educacional, e o terceiro seria o específico.

Um trecho de diário só é retornado quando pelo menos um dos sinônimos de cada um dos três  conjuntos aparecem próximos uns dos outros (sugiro 20 palavras de distância, mas é modificável).

Todas essas queries poderiam ser uma só (e pro Elasticsearch se tornarão apenas uma mesmo, pra evitar aquele problema de trechos repetidos). As divisões feitas aqui são pra melhorar nosso entendimento sobre o que está sendo buscado. Ex: em `Conectividade` e em outros subtemas o primeiro term_set diz respeito às tecnologias e o segundo às empresas/instituições/programas que atuam naquele subtema. E a própria divisão em subtemas também é pra facilitar nosso entendimento.

[Link do documento no Google Docs que permite comentários](https://docs.google.com/document/d/1BT2oi8HQkUpXVeWMnYrQLKNnkgSQJLYEI6pOYG2jOjA/edit?usp=sharing).

**Comment by adanibello** [comment]
@giuliocc obrigada!

Revisei os termos e deixei vários comentários com sugestões e algumas dúvidas. Em resumo:
- inclusão de alguns termos no grupo principal de cada conjunto de busca, para abranger a diversidade de publicações e instrumentos que estamos buscando nos DOs;
- algumas palavrinhas-chave a mais ou a menos para ajustar o escopo de cada subtema;
- dúvidas sobre a cobertura das diferentes grafias de alguns fornecedores;
- dúvidas leigas no subtema de robótica;
- sugestões de alterações mais extensas no subtema de acessibilidade e reflexões sobre o escopo (o caminho que estou seguindo ali é para pegar tanto a dimensão relacionada à pessoas com deficiência, como à inclusão digital de forma mais ampla).

Dê uma olhadinha e, caso queira aprofundar algum deles, me chame (;

**Comment by ogecece** [comment]
@adanibello aceitei a grande maioria das sugestões e deixei alguns comentários:
- Na parte de "Formação e Aprendizagem" talvez criar um `term_set` com dois grupos pra poder pegar melhor "ensino remoto", "ensino à distância" e "ead"
- Sobre dar muita interseção com "secretaria", talvez eliminar os termos "educação" e "educacional" na busca por "Infraestrutura e Dispositivos"
- Remover "sensor" e "led" e inserir "microcontrolador" na busca por "Robótica"

**Comment by adanibello** [comment]
@giuliocc concordei com suas sugestões em Robótica!

Sobre a sugestão em Formação e Aprendizagem, não creio que precise criar outro grupo. Pela experiência do ano passado, deixar essa condicionante para esses três termos abre margem pra muita coisa fora do escopo (porque esses termos aparecem em muitas ações de outras secretarias).... acho que entrando no terceiro grupo, como sugeri ali, associado com os outros termos que colocamos nos demais grupos, a tendência é direcionar mais o escopo (bem, é uma aposta rs)

Por fim, sobre essa questão de equipamentos para as secretarias, acredito que seja mesmo um ônus -- o de aumentar o volume de resultados -- que vamos ter de lidar. Tirando os termos do segundo grupo, temo que a gente perca registros importantes sobre a aquisição (que é centralizada nas secretarias de educação, geralmente)... É possível que a gente possa pegar a distribuição, porque esse repasse deve (ou deveria) estar registrado no DO, já que ele necessariamente está vinculado a um processo administrativo...  Mas acho melhor não arriscarmos. Minha sugestão é mantermos mesmo os termos!

**Comment by ogecece** [comment]
Fechou! Vou fechar a issue. [Este documento](https://docs.google.com/document/d/1BT2oi8HQkUpXVeWMnYrQLKNnkgSQJLYEI6pOYG2jOjA/edit?usp=sharing) já é o conjunto de queries mencionado em #16 para montar #18 .
