### ISSUE TITLE
Corrigir entradas faltantes na base de CNPJ

### ISSUE THREAD

**Issue by ogecece** [okfn-brasil/observatorio-materiais#15]
### Descrição

Alguns CNPJs que estão na base da RFB não estão disponíveis na tabela `resposta_cnpj` como `00.000.000/0001-91` (Banco do Brasil) ou `19.131.243/0001-97` (Open Knowledge Brasil).

### Objetivo

Completar a carga de CNPJs disponíveis na nossa base para que todos os CNPJs cadastrados na RFB estejam disponíveis por meio da API do QD.

### Definição de "pronto"
- Carga de CNPJs na base `resposta_cnpj` iniciada com correções realizadas

**Comment by tigreped** [comment]
Houve inconsistências entre as tabelas de empresas e estabelecimentos. Criar um processo complementar para garantir que todos os arquivos zip sejam baixados e processados, idealmente inclusive com verificação de checksum dos arquivos, com relação à última execução/carga e notificação caso haja erros ou inconsistências.

**Comment by trevineju** [comment]
O status da tarefa está como 'feito' então podemos fechar essa issue, certo?
