### ISSUE TITLE
Acompanhar carga de novas entradas na base de CNPJ

### ISSUE THREAD

**Issue by ogecece** [okfn-brasil/observatorio-materiais#17]
### Descrição

As atividades #14 e #15 irão iniciar uma nova carga nas tabelas `resposta_cnpj` e `resposta_socios`. Possíveis erros podem ser identificados e corrigidos.

### Objetivo

Corrigir possíveis erros nas novas cargas nas tabelas de CNPJ.

### Definição de "pronto"
- Carga de CNPJs na base `resposta_cnpj` e `resposta_socios` finalizadas com sucesso

**Comment by tigreped** [comment]
Realizada uma última carga após as correções de [#14](https://github.com/okfn-brasil/observatorio-materiais/issues/14), concluída aos 04/07/22, contornando inclusive a ausência das entradas da base de estabelecimentos com uma geração do dv para a empresa. 

A carga resultou com 100% de sucesso, num total de 48.828.011 empresas/estabelecimentos carregadas para a tabela resposta_cnpj e um total de 21.280.707 para a tabela resposta_socios;

Após a implementação de [#23](https://github.com/okfn-brasil/observatorio-materiais/issues/23), deve ser realizada uma nova carga a ser monitorada por aqui.
