### ISSUE TITLE
Definição da metodologia da análise #1

### ISSUE THREAD

**Issue by ogecece** [okfn-brasil/observatorio-materiais#20]
### Descrição
Para a realização de #11 , uma categorização é usada para classificar e agrupar resultados os resultados, de forma a facilitar a análise.

### Objetivo
Adequar a categorização utilizada em etapa anterior (piloto) para o atual escopo de análise, que é mais amplo (=implantação de tecnologias na Educação municipal).

### Definição de "pronto":
Itens da categorização atualizados.

**Comment by adanibello** [comment]
Como havia comentado ali na #18 , nossa análise partiu da categorização construída anteriormente, estruturada da seguinte forma:

Item | Descrição | Classificação
-- | -- | --
Escopo | Indica se o resultado obtido está ou não dentro do escopo da investigação. | "Sim" ou "Não'"
Objeto | Indica a natureza da tecnologia à qual o resultado se refere. | "Solução de software" ou "Tecnologia de infraestrutura"
Categoria | Indica se o resultado está relacionado às diretrizes e normas para a ação do poder público ou a processos que envolvam arranjos contratuais. Em outros termos, responde à pergunta "o que está sendo feito?" | "Aquisição e serviços" e "Políticas e normas"
Formato | Indica a forma pela qual o poder público operacionalizou a ação ou processo. Em outros termos, responde à pergunta "como está sendo feito?". | "Comodato"; "Contratação direta"; "Doação"; "Parceria"; "Legislação"; "Outros"
Tipo de publicação | Indica o meio pelo qual a ação ou processo ao qual o resultado se refere foi publicizado em diário oficial. Em outros termos, responde à pergunta "Como foi oficializado e/ou publicizado?". | "Ata"; "Comunicado"; "Contrato"; "Decreto"; "Deliberação"; "Despacho"; "Edital"; "Extrato"; "Instrução normativa"; "Lei"; "Portaria; "Regimento"; "Resolução"; "Termo"; "Veto"; "Outros"
Nome/número | Nome e número da norma, em caso de políticas e normas, ou do documento, no caso de contratos, termos e processos administrativos. | NA (campo aberto)
Contratada/parceira/ doadora | Nome de contratadas, parceiras ou doadoras atuando no fornecimento, desenvolvimento e/ou implantação de tecnologias, ou ainda na execução de iniciativas relacionadas. | NA (campo aberto)
Fornecedora | Fornecedora do bem ou serviço quando diferente da contratada, parceira ou doadora. | NA (campo aberto)
Observação | Comentários sobre o resultado, seja em relação a possíveis aprimoramentos na busca, seja em relação a casos de interesse para aprofundamento na análise. | NA (campo aberto)
Resultado duplicado | Indica se o resultado apareceu relacionado anteriormente, em decorrência de duas razões: i) combinações diferentes de palavras-chave levaram às mesmas publicações nos diários oficiais; ii) publicações mais longas, como leis ou planos estratégicos, apresentavam as mesmas palavras-chave em trechos diferentes, mas distantes entre si, fazendo com que os resultados fossem compreendidos pelos robôs de busca como distintos. | "Sim" ou "Não'"

<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px !important; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></p>

**Comment by adanibello** [comment]
Com o início das análises da base #18 , fizemos alguns ajustes mais estruturais:

- atualizamos o item "objeto" para "tipo de objeto", mantendo esta como uma classificação mais genérica;
- adicionamos o item "objeto", mais específico, já que fornece mais detalhes: por exemplo, pode ser "aplicativo ou plataforma digital"; "formação"; "diretrizes pedagógicas"; "equipamento de informática"; etc. As classificações estão sendo completadas a medida que avançamos na análise.
- adicionamos o item "abrangência", para classificar se o resultado diz respeito a toda a rede municipal, a uma escola específica ou ao órgão central (secretaria de educação);
- por fim, adicionamos o item "modalidade/hipótese" para maior detalhamento das contratações.

Também estamos atualizando a lista de classificações dos demais itens, incluindo novas opções. Esse processo será contínuo, até o fim dessa primeira etapa de análise e produção de relatórios.
