### ISSUE TITLE
Análise dos resultados #1

### ISSUE THREAD

**Issue by adanibello** [okfn-brasil/observatorio-materiais#25]
DESCRIÇÃO:
Análise total dos resultados obtidos em #18 e #29. As buscas têm como base os termos discutidos em #13, e será realizada para as 27 cidades [disponíveis](https://ok.org.br/noticia/porto-alegre-petrolina-e-mais-confira-as-novas-cidades-do-querido-diario/) no Querido Diário até a primeira quinzena de maio, no período de jan/20 a abr/22. Para análise, considera-se também os pontos identificados na análise inicial (#11).

OBJETIVOS:
- Analisar a base de dados em sua totalidade, categorizando os resultados de acordo com seu escopo e "etiquetando" os resultados positivos de acordo com a relação de itens e classificações:

**1.  Abrangência** ("Rede municipal", "Escola, "Órgão Central")
**2. Tipo de Objeto** ("Solução de software"; "Tecnologia de infraestrutura"; "Política de conectividade"; "Práticas educacionais")
**3. Objeto** ("Ajuda de custo"; "Aparelho celular ou smartphone"; "Aplicativo ou plataforma digital"; "Cessão de uso ou aquisição de licenças"; "Contratação e desenvolvimento de sistemas"; "Chromebook"; "Cursos para estudantes"; "Diretrizes pedagógicas"; "Equipamento de informática"; "Equipamento de realidade virtual"; "Formação"; "Infraestrutura para serviços de internet"; "Kit de robótica ou robôs"; "Lousa digital e projetor interativo"; "Manutenção de sistemas"; "Recursos didáticos para programação"; "Serviços de suporte técnico"; "Serviço de internet"; "Transmissão de aulas")
**4. Categoria** ("Aquisição e serviços" e "Políticas e normas")
**5. Formato** ("Comodato"; "Contratação direta"; "Doação"; "Parceria"; "Legislação"; "Licitação"; "Outros"; "Não Identificado")
**6. Modalidade** ("Dispensa"; "Inexigibilidade"; "Fomento (MROSC)"; "Pregão"; 'N/A"; "Registro de Preço"; "Tomada de Preço"; "Credenciamento"; "Convite"; "Não Identificado")
**7. Tipo de publicação** ("Ata"; "Comunicado"; "Contrato"; "Decreto"; "Deliberação"; "Despacho"; "Edital"; "Extrato"; "Instrução normativa"; "Lei"; "Notificação"; "Portaria"; "Rescisão"; "Regimento"; "Resolução"; "Termo"; "Veto"; "Outros")
**8. Nome/número**
**9. Contratada/parceira/doadora
10. Fornecedora 
11. Observações**

- Tornar a categorização o mais robusta possível neste estágio, visando à futura automação das classificações (base será insumo para algoritmo a ser desenvolvido).

DEFINIÇÃO DE PRONTO
Todos os resultados analisados e com categorização amplamente preenchida, identificando aqueles que atendem ao escopo previsto para o primeiro relatório (#4), potenciais casos de interesse para desdobramento nos relatórios, além de ocorrências de problemas e indicações de melhorias para refinamento de buscas futuras, caso haja.

**Comment by micoimbra** [comment]
A análise dos resultados se desdobrou na **produção de visualizações para o primeiro relatório** (análise panorâmica). Para isso, algumas tarefas foram realizadas:
- Padronização da categorização da base (em especial os campos em que não se aplicam categoria (N/A) ou informações não foram identificadas ("Não identificado")
- Eliminação de duplicatas, deixando-as salvas em arquivo paralelo 
- Ajuste do subtema, quando necessário 
- Adequação de tipos de objeto e objeto, quando necessário 
- Seleção de casos interessantes, em cada cidade e transversais, para compor a análise panorâmica, considerando casos de interesse por parte do ecossistema

A partir deste trabalho a análise panorâmica se consolidou em **"Panorama 1: Radar das tecnologias da educação nos municípios"** com as seguintes seções:
- Panorama das buscas: _visão geral dos resultados e indicadores_
- Entrou no radar!: _casos que podem ser de interesse para o ecossistema ou aprofundados em análises futuras_
- Na ordem do dia: _tendências de tecnologias adotadas nas cidades analisadas - não necessariamente boas práticas no campo e, por isso, também merecem atenção_
- Para ligar o alerta: _casos de atenção para falhas de transparência e integridade (potenciais ou explícitos)_
