### ISSUE TITLE
Analisar novo dataset

### ISSUE THREAD

**Issue by adanibello** [okfn-brasil/observatorio-materiais#29]
DESCRIÇÃO:
Análise dos resultados obtidos (arquivo "dataset3"). As buscas têm como base os termos atualizados para resultados mais precisos e será realizada para as 27 cidades [disponíveis](https://ok.org.br/noticia/porto-alegre-petrolina-e-mais-confira-as-novas-cidades-do-querido-diario/) no Querido Diário. 

OBJETIVOS:
Analisar a nova base de dados categorizando os resultados de acordo com seu escopo, priorizando:
- Os municípios com alto número de resultados encontrados na base antiga (Rio de Janeiro, Curitiba, Jundiaí);
- Os municípios não iniciados na base antiga: Goiânia, Maceió, Palmas e Florianópolis;

Tornar a categorização o mais robusta possível neste estágio, visando à futura automação das classificações (base será insumo para algoritmo a ser desenvolvido).

DEFINIÇÃO DE PRONTO:
Todos os resultados analisados e com categorização amplamente preenchida, identificando aqueles que atendem ao escopo previsto para o primeiro relatório (https://github.com/okfn-brasil/observatorio-materiais/issues/4), potenciais casos de interesse para desdobramento nos relatórios, além de ocorrências de problemas e indicações de melhorias para refinamento de buscas futuras, caso haja.

**Comment by micoimbra** [comment]
- [x] A análise dos resultados obtidos foi **concluída** no dia **23/09**.

No total, foram analisados 1.533 resultados em 27 municípios. Diferentemente do planejado inicialmente, optamos por analisar também os municípios que já haviam sido categorizados na análise da outra base, com o intuito de identificar os avanços do refinamento das buscas de forma ampla.

- O % de resultados dentro do escopo cresceu em 26 dos 27 municípios. Apenas em Belo Horizonte (MG), única cidade em que não houve melhora, as buscas seguem não retornando resultados relevantes. A distribuição fica da seguinte forma:
      - 10 cidades têm ao menos 63% dos resultados dentro do escopo.
      - 3 cidades têm entre 44% e 59% dos resultados dentro do escopo.
      - 10 cidades têm entre 23% e 39% dos resultados dentro do escopo.
      - 4 cidades têm menos de 9% dos resultados dentro do escopo.

A média geral de resultados dentro do escopo foi de 39%.
Se comparadas as cidades cujas entradas foram analisadas na íntegra na primeira base gerada para esta, a média subiu de 20% para 44%.

- Foram observadas algumas ocorrências de resultados iguais, mas classificados em subtemas diferentes (ou seja, diferentes combinações de termos de busca levaram aos mesmos resultados). 

- De forma geral, a base analisada demonstrou que a revisão dos termos de busca trouxe mais precisão para os resultados. Há ainda mais possibilidades de aprimoramento. Dentre os resultados fora do escopo, há predomínio de publicações relacionadas à telefonia fixa, concursos, cursos técnicos, atas de conselho municipal, e atividades EAD em geral. 

- Em números absolutos, as cidades com **maiores** números de resultados são: 
       - Rio de Janeiro (RJ): 180
       - Florianópolis (SC): 154
       - Araguaína (TO): 133
       - Curitiba (PR): 122
       - Brasília (DF): 111
       - Jundiaí (SP): 103
- As cidades com **menores** números de resultados são: 
       - Campo Grande (MS): 19
       - Jaboatão dos Guararapes (PE): 16
       - Feira de Santana (BA): 14
       - Belo Horizonte (MG): 10
       - João Pessoa (PB): 8
       - Caxias (MA): 3
As demais apresentam entre 22 e 88 resultados cada (média de 44/cidade).

- Alguns exemplos de casos de interesse identificados: aquisição de robôs e kits de robótica; contratação de sistemas de gestão educacional; aquisição de licenças Google for Education e G Suite for Education; desenvolvimento de plataformas e aplicativos próprios para atender a rede municipal de ensino; aquisição de notebooks, tablets e chromebooks; contratação de serviços de internet e casos com problemas potenciais ou explícitos de transparência e integridade.
