### ISSUE TITLE
Montar quadro no Miro

### ISSUE THREAD

**Issue by giuliocc** [okfn-brasil/observatorio-materiais#3]
Quadro direcionará #7 . 

Como a reunião será feita em etapas, o quadro deve conter instruções sobre cada etapa, assim como todo o material necessário para que as participantes consigam interagir durante a Oficina.

**Comment by ogecece** [comment]
[Link para o quadro](https://miro.com/app/board/uXjVO1eMgMk=/?share_link_id=829753347681) (ainda em esboço).

**Comment by ogecece** [comment]
Quadro finalizado, fechando a issue.
