### ISSUE TITLE
Elaborar proposta de primeira análise a ser realizada

### ISSUE THREAD

**Issue by giuliocc** [okfn-brasil/observatorio-materiais#4]

**Comment by ogecece** [comment]
Proposta descrita em #3. Podemos fechar @adanibello ? Ou quer documentar algo a mais aqui?

**Comment by adanibello** [comment]
Por conta da natureza desta primeira análise, alguns pontos do escopo já estão pré-definidos.
Esta é a que chamamos de "análise periódica", que busca trazer uma visão panorâmica da implantação de tecnologias na educação municipal. Ela também nos indicará temas e casos relevantes para serem aprofundados na outra categoria de análise, que chamamos de "temática". Já em relação à classificação dos resultados, que inclui categorizar publicações e atos encontrados nos Diários Oficiais, estamos nos baseando no trabalho realizado anteriormente, em fase piloto. 
Assim, temos como escopo:
- Temático: Implantação de tecnologias na Educação municipal (quaisquer menções são resultados de interesse).
- Cronológico: Jan/2020 a abr/2022 (mês anterior ao início da análise).
- Espacial: 27 cidades já disponíveis no QD.
- Tipos de objeto (natureza da tecnologia): Soluções de software e tecnologias de infraestrutura.
- Categoria (relacionado às publicações oficiais): "Aquisições de serviços" e "Políticas e Normas"
