### ISSUE TITLE
Fazer uma pré-análise baseada no dataset enviado por IC

### ISSUE THREAD

**Issue by giuliocc** [okfn-brasil/observatorio-materiais#5]
A partir dos dados fornecidos por #1 , fazer uma avaliação do escopo do tema do último piloto para auxiliar no preparo de #4 .

**Comment by adanibello** [comment]
@giuliocc sobre essa primeira versão dos resultados, fiz um olhar bastante transversal e mais exploratório, só para ter uma base do que veio nessa primeira leva. Registrando os comentários aqui, que fiz previamente à oficina da semana passada:

1. Das 2330 entradas, 1298 são únicas. Mantendo nessa média, não acho tão difícil fazermos uma análise que passe por todos os resultados, ao menos nesse primeiro momento. Mas ainda precisamos avaliar com a base completa, com os novos inputs coletados na oficina. 

2. As datas de publicação realmente fazem toda diferença, fica mais fácil navegar e só de bater o olho já dá pra localizar o que é repetido ou não, quais são excertos de uma mesma publicação... a inclusão dos links originais também ficou ótima.

3. Senti falta de saber os termos que estão relacionados ao resultado. Eles ajudam a entender o que vem de cada combinação, inclusive aquelas mais promissoras e as que retornam resultados menos úteis. Por exemplo, os primeiros resultado da base são do DO de Floripa, um extrato de aditivo de termo de colaboração de uma OSC para atendimento de educação infantil, seguido por vários similares, de outras instituições para EI e EJA. Não compreendo porque esse resultado veio nas buscas (talvez, chutando aqui, porque tem educação e plataforma no texto?). Então, pediria para voltarmos as colunas de termos principal e secundários. 

4. Me chamou atenção a quantidade de resultados fora do escopo. A título de exemplo, BH teve 41 resultados, dos quais 25 eram únicos. 33/41 estavam fora do escopo. Dos 8 restantes, tínhamos 4 válidos (que não se repetiam). Acho que seria bom fazermos uma etapa de revisão das combinações de termos antes de rodarmos as buscas, que acha? Vocês fazem uma proposta e a gente revisa. Lembro que no piloto algumas combinações nos pareciam menos exitosas porque traziam termos que não necessariamente apareceriam juntos.

**Comment by adanibello** [comment]
@giuliocc podemos fechar esta ou você gostaria de comentar os pontos levantados aqui?
