### ISSUE TITLE
Elaborar propostas de funcionalidades pro MVP da plataforma

### ISSUE THREAD

**Issue by giuliocc** [okfn-brasil/observatorio-materiais#6]
Montar documento (preferencialmente gráfico) que contenha algumas ideias para a primeira versão da plataforma do projeto. Estimando cerca de 4 sprints de desenvolvimento.

**Comment by ogecece** [comment]
Propostas elaboradas, desenho feito no quadro do Miro em #3 . Fechando a issue.
