### ISSUE TITLE
Oficina de trabalho #1 (Abr/22)

### ISSUE THREAD

**Issue by giuliocc** [okfn-brasil/observatorio-materiais#7]
A oficina terá formato parecido com as feitas para os pilotos, porém, nesta discutiremos menos palavras-chave e mais o escopo e expectativas para as primeiras entregas.

A oficina durará 2h (18/05, 14h-16h BRT) e será conduzida pela OKBR.

Tarefas relacionadas:
- #3 
- #4 
- #6

**Comment by ogecece** [comment]
Oficina realizada. Resultado em #3. Fechando a issue.
